journey = Journey.first

Quest.create!([
  {
    name: "For Loops",
    story: "<div>In the illuminated darkness of the sprawling metropolis known as Night City, a lone figure named Soledad moved stealthily. Soledad wasn’t an average citizen; she was a mercenary with an augmented cybernetic body honed for fighting crime. Her mission was to annihilate a series of notorious cyber criminals wreaking havoc in Night City.<br><br>Soledad had a list of the criminals, virtually pasted in the HUD of her cybernetic eye. Her advanced neural processor was set to systematically filter through each name, prioritizing on basis of the threat level they posed to the city. To an outsider, this process would seem a lot like a 'for loop' in coding where the machine systematically moves through each data point to analyse or modify it.<br><br>As Soledad navigated the grim alleys and neon-lit skies of Night City, she came across a pattern. Each criminal bore the mark of what was a seemingly defunct secret organization, the \"Phantom Liberty\". This intriguing piece of information sent our mercenary on a deeper and more dangerous path.<br><br>With each member of the \"Phantom Liberty\" she encountered, Soledad made sure to record their details for future reference. It was as if her neural processor had another list where each encounter was systematically logged in just like appending new elements to an array. <br><br>Despite the risks, Soledad plunged further into this mission, her determination fueled by the growing threat of \"Phantom Liberty\". While the embedded neural processor handled the systematic analysis and logging, Soledad focused on understanding the intricate web woven by this organization and their ultimate goal in Night City.<br><br>This continued commitment of Soledad to systematically dismantle the organization mirrors the way a 'for loop' functions in code executing a set of instructions repeatedly until a certain condition is met. Her meticulousness and persistence against the dangers mirror a programmer's endeavor in solving complex problems using the fundamentals of coding. <br><br>Just as Soledad assists the city of Night City, so too does the 'for loop' aid programmers in many crucial tasks. The dedication to a systematic and methodological approach, the relentless pursuit of an end goal, and the use of established principles reflect the essence of both Soledad's character and the concept of 'for loop' in programming. </div>",
    task: "https://academy.solidkraft.com/lessons/module-1/js-for-loops.html",
    journey_id: journey.id
  },
])

p "Created #{Quest.count} quests"